### ISSUE TITLE
Running in containers

### ISSUE THREAD

**Issue by coquinone** [loopyd/install-grass#10]
Hi
Any idea what Grass configurations are required to run this in a ubuntu container? 
Would love to run this it without a gui.

Thanks

**Comment by ardynatz** [comment]
Hey, i have tried to use it on my Ubuntu 22.04 VM without GUI, but it seems impossible without using any Desktop container since grass will shown as Desktop App.
You need at least Desktop container like gnome,kde,etc to be able run grass Desktop App.

**Comment by loopyd** [comment]
Hi yeah, the grass desktop node binary needs an active xsession to function.  You won't be able to run it headless, unfortunately.

**Comment by loopyd** [comment]
Can't fix this one due to limitations of Desktop Node binary.
