### ISSUE TITLE
missing the equivilent ca-certificates package problem

### ISSUE THREAD

**Issue by jgrnot** [loopyd/install-grass#15]
![image](https://github.com/user-attachments/assets/785294e4-4ebd-4190-8f6e-0db18b476c37)

**Comment by loopyd** [comment]
Hi there.  

Here are the package names for ca-certificates in different Linux distributions:

- **Ubuntu/Debian**: `ca-certificates`
- **Fedora**: `ca-certificates`
- **CentOS/RHEL**: `ca-certificates`
- **Arch Linux**: `ca-certificates`
- **openSUSE**: `ca-certificates`
- **Alpine Linux**: `ca-certificates`

You can install these packages using the respective package manager for each distribution. For example:

- **Ubuntu/Debian**:
  ```sh
  sudo apt-get install ca-certificates
  ```

- **Fedora**:
  ```sh
  sudo dnf install ca-certificates
  ```

- **CentOS/RHEL**:
  ```sh
  sudo yum install ca-certificates
  ```

- **Arch Linux**:
  ```sh
  sudo pacman -S ca-certificates
  ```

- **openSUSE**:
  ```sh
  sudo zypper install ca-certificates
  ```

- **Alpine Linux**:
  ```sh
  sudo apk add ca-certificates
  ```
  
  The script may also prompt you about missing dependencies.  We don't automate this step as package manager and package name will be different depending on your Linux distrobution.

**Comment by 0xsoydev** [comment]
> Hi there.
> 
> You can install these packages using the respective package manager for each distribution. For example:
> 
> * **Ubuntu/Debian**:
>   ```shell
>   sudo apt-get install ca-certificates
>   ```
> * **Fedora**:
>   ```shell
>   sudo dnf install ca-certificates
>   ```
> * **CentOS/RHEL**:
>   ```shell
>   sudo yum install ca-certificates
>   ```
> * **Arch Linux**:
>   ```shell
>   sudo pacman -S ca-certificates
>   ```
> * **openSUSE**:
>   ```shell
>   sudo zypper install ca-certificates
>   ```
> * **Alpine Linux**:
>   ```shell
>   sudo apk add ca-certificates
>   ```
> 
> The script may also prompt you about additional missing dependencies. We don't automate this step as package manager and package name will be different depending on your Linux distrobution.

For Arch Linux:
`update-ca-certificates` command isn't available in the `ca-certificates` core package, instead it is `update-ca-trust', I changed that for my setup and it worked flawlessly
