### ISSUE TITLE
chmod: cannot access './install-grass.sh': No such file or directory

### ISSUE THREAD

**Issue by vfa-gianglt-hcm** [loopyd/install-grass#9]
How to fix this issue, please help me thanks.
root@vmi1234:~/install-grass# chmod +x ./install-grass.sh
chmod: cannot access './install-grass.sh': No such file or directory

**Comment by ardynatz** [comment]
Hey, do you on the right directory or path? First make sure you are on the right directory where install-grass located :)

**Comment by vfa-gianglt-hcm** [comment]
> Hey, do you on the right directory or path? First make sure you are on the right directory where install-grass located :)

Yes, right directory , I follow "git clone https://github.com/loopyd/install-grass.git
cd install-grass
chmod +x ./install-grass.sh
sudo ./install-grass.sh"
 I copy & paste 😬 I am using ubuntu 22.4.0 
I check file sh on the web https://www.shellcheck.net/ I see the error Don't know if this is the cause

**Comment by ardynatz** [comment]
Your current problem doesn't looks like coming from the .sh file, Can you provide a screenshot like this? just to clarify that you're on the right path/directory.

![image](https://github.com/user-attachments/assets/580b9055-82e4-49c0-afe1-414addd69bdf)

**Comment by vfa-gianglt-hcm** [comment]
> Your current problem doesn't looks like coming from the .sh file, Can you provide a screenshot like this? just to clarify that you're on the right path/directory.
> 
> ![image](https://private-user-images.githubusercontent.com/77366357/354882886-580b9055-82e4-49c0-afe1-414addd69bdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NTU5ODUsIm5iZiI6MTcyMjc1NTY4NSwicGF0aCI6Ii83NzM2NjM1Ny8zNTQ4ODI4ODYtNTgwYjkwNTUtODJlNC00OWMwLWFmZTEtNDE0YWRkZDY5YmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA3MTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYmY2NDhhYzY5MDUyYTM0NGM5MTgyYjc1NzIwZGE4MmRmNTIxMzVhYjNhMTVlNjM0NmFhZjljNGFlNDhmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8D-ZFNkUvOSeWsLWx65RngredDCpHAoRwx1E3KWkVok)

Sure, this my screenshot
![Screenshot 2024-08-04 at 2 14 29 PM](https://github.com/user-attachments/assets/a7e285b9-83b0-4135-95b6-0b18a52adf92)

**Comment by ardynatz** [comment]
I see the problem, i will update the Installation guide ASAP. The problem is coming from the file name, previously it's `install-grass.sh` and now it's `install.sh`.
Now you can run this by `chmod +x ./install.sh`lmk if you run into a problem :)

**Comment by vfa-gianglt-hcm** [comment]
> I see the problem, i will update the Installation guide ASAP. The problem is coming from the file name, previously it's `install-grass.sh` and now it's `install.sh`. Now you can run this by `chmod +x ./install.sh`lmk if you run into a problem :)

I see, I update it's working good, thanks you.
